

DROP TABLE TB_BOARD CASCADE CONSTRAINTS;
DROP TABLE TB_MEMBER CASCADE CONSTRAINTS;
DROP TABLE TB_COMMENT CASCADE CONSTRAINTS;
DROP TABLE TB_FILE CASCADE CONSTRAINTS;
DROP TABLE TB_BOARD_TYPE CASCADE CONSTRAINTS;

CREATE TABLE "TB_BOARD" (
	"B_NO"	        NUMBER		                    NOT NULL,
	"B_TITLE"	    VARCHAR2(100)		            NOT NULL,
	"B_CONTENT"	    VARCHAR2(1000)		            NOT NULL,
	"B_WRITER"	    VARCHAR2(60)		            NOT NULL,
	"B_WRITE_DATE"	TIMESTAMP	DEFAULT SYSDATE	    NOT NULL,
	"B_COUNT"	    NUMBER	        DEFAULT 0	    NOT NULL,
	"M_ID"	        VARCHAR2(20)		            NULL,
	"BT_NO"	        NUMBER		                    NOT NULL
);

CREATE TABLE "TB_MEMBER" (
	"M_ID"	        VARCHAR2(20)		NOT NULL,
	"M_NICKNAME"	VARCHAR2(60)		NOT NULL,
	"PASSWORD"	    VARCHAR2(20)		NOT NULL
);

CREATE TABLE "TB_COMMENT" (
	"C_NO"	        NUMBER		                NOT NULL,
	"B_NO"	        NUMBER		                NOT NULL,
	"M_ID"	        VARCHAR2(20)		        NOT NULL,
	"C_WRITER"	    VARCHAR2(60)		        NOT NULL,
	"C_WRITE_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"C_COMMENT" 	VARCHAR2(300)		        NOT NULL,
    "C_LEVEL"       NUMBER      DEFAULT 0       NOT NULL,
    "C_REF"         NUMBER                      NULL,
    "C_SEQ"         NUMBER      DEFAULT 0       NOT NULL
);

CREATE TABLE "TB_FILE" (
	"F_NO"	        NUMBER		                NOT NULL,
	"F_ORIGINAL_FILENAME"	VARCHAR2(600)		NOT NULL,
    "F_RENAME_FILENAME"	VARCHAR2(600)		    NOT NULL,
	"F_DATE"	    DATE	DEFAULT SYSDATE	    NOT NULL,
	"B_NO"	        NUMBER		                NOT NULL
);

CREATE TABLE "TB_BOARD_TYPE" (
	"BT_NO"	    NUMBER		        NOT NULL,
	"BT_NAME"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "TB_BOARD"."B_WRITER" IS 'MEMBER(M_NICKNAME)';

COMMENT ON COLUMN "TB_BOARD"."BT_NO" IS '1. 자유게시판, 2.공지, 3.유머, 4.뉴스';

COMMENT ON COLUMN "TB_COMMENT"."C_WRITER" IS 'MEMBER(M_NICKNAME)';

COMMENT ON COLUMN "TB_COMMENT"."C_REF" IS 'TB_COMMENT(C_NO)';

COMMENT ON COLUMN "TB_COMMENT"."C_LEVEL" IS '원글 0, 원글의 댓글 1, 댓글의 댓글 2 ';

COMMENT ON COLUMN "TB_COMMENT"."C_SEQ" IS '댓글 순서 ';

COMMENT ON COLUMN "TB_BOARD_TYPE"."BT_NO" IS '1. 자유게시판, 2.공지, 3.유머, 4.뉴스';

ALTER TABLE "TB_BOARD" ADD CONSTRAINT "PK_TB_BOARD" PRIMARY KEY (
	"B_NO"
);

ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"M_ID"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "PK_TB_COMMENT" PRIMARY KEY (
	"C_NO"
);

ALTER TABLE "TB_FILE" ADD CONSTRAINT "PK_TB_FILE" PRIMARY KEY (
	"F_NO"
);

ALTER TABLE "TB_BOARD_TYPE" ADD CONSTRAINT "PK_TB_BOARD_TYPE" PRIMARY KEY (
	"BT_NO"
);

ALTER TABLE "TB_BOARD" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_BOARD_1" FOREIGN KEY (
	"M_ID"
)
REFERENCES "TB_MEMBER" (
	"M_ID"
);

ALTER TABLE "TB_BOARD" ADD CONSTRAINT "FK_TB_BOARD_TYPE_TO_TB_BOARD_1" FOREIGN KEY (
	"BT_NO"
)
REFERENCES "TB_BOARD_TYPE" (
	"BT_NO"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_TB_BOARD_TO_TB_COMMENT_1" FOREIGN KEY (
	"B_NO"
)
REFERENCES "TB_BOARD" (
	"B_NO"
)ON DELETE CASCADE;

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_COMMENT_1" FOREIGN KEY (
	"M_ID"
)
REFERENCES "TB_MEMBER" (
	"M_ID"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_TB_COMMENT_TO_TB_COMMENT_1" FOREIGN KEY (
	"C_REF"
)
REFERENCES "TB_COMMENT" (
	"C_NO"
);

ALTER TABLE "TB_FILE" ADD CONSTRAINT "FK_TB_BOARD_TO_TB_FILE_1" FOREIGN KEY (
	"B_NO"
)
REFERENCES "TB_BOARD" (
	"B_NO"
)ON DELETE CASCADE;