

DROP TABLE TB_BOARD;
DROP TABLE TB_MEMBER;
DROP TABLE TB_COMMENT;
DROP TABLE TB_FILE;
DROP TABLE TB_BOARD_TYPE;

CREATE TABLE "TB_BOARD" (
	"B_NO"	        NUMBER		                    NOT NULL,
	"B_TITLE"	    VARCHAR2(100)		            NOT NULL,
	"B_CONTENT"	    VARCHAR2(1000)		            NOT NULL,
	"B_WRITER"	    VARCHAR2(60)		            NOT NULL,
	"B_WRITE_DATE"	TIMESTAMP	DEFAULT SYSDATE	    NOT NULL,
	"B_COUNT"	    NUMBER	        DEFAULT 0	    NOT NULL,
	"M_ID"	        VARCHAR2(20)		            NULL,
	"B_PASSWORD"	NUMBER	DEFAULT 0000	        NULL,
	"BT_NO"	        NUMBER		                    NOT NULL,
    "IS_MEMBER"     VARCHAR2(2) DEFAULT 'Y'         NOT NULL
);

CREATE TABLE "TB_MEMBER" (
	"M_ID"	        VARCHAR2(20)		NOT NULL,
	"M_NICKNAME"	VARCHAR2(60)		NOT NULL,
	"PASSWORD"	    VARCHAR2(20)		NOT NULL
);

CREATE TABLE "TB_COMMENT" (
	"C_NO"	        NUMBER		                NOT NULL,
	"B_NO"	        NUMBER		                NOT NULL,
	"M_ID"	        VARCHAR2(20)		        NOT NULL,
	"C_WRITER"	    VARCHAR2(60)		        NOT NULL,
	"C_WRITE_DATE"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"C_COMMENT" 	VARCHAR2(300)		        NOT NULL,
    "IS_MEMBER"     VARCHAR2(2) DEFAULT 'Y'     NOT NULL
);

CREATE TABLE "TB_FILE" (
	"F_NO"	        NUMBER		            NOT NULL,
	"F_DIRECTORY"	VARCHAR2(600)		    NOT NULL,
	"F_DATE"	    DATE	DEFAULT SYSDATE	NOT NULL,
	"B_NO"	        NUMBER		            NOT NULL
);

CREATE TABLE "TB_BOARD_TYPE" (
	"BT_NO"	    NUMBER		        NOT NULL,
	"BT_NAME"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "TB_BOARD"."B_WRITER" IS 'MEMBER(M_NICKNAME)';

COMMENT ON COLUMN "TB_BOARD"."BT_NO" IS '1. 자유게시판, 2.공지, 3.유머, 4.뉴스';

COMMENT ON COLUMN "TB_COMMENT"."C_WRITER" IS 'MEMBER(M_NICKNAME)';

COMMENT ON COLUMN "TB_BOARD_TYPE"."BT_NO" IS '1. 자유게시판, 2.공지, 3.유머, 4.뉴스';

ALTER TABLE "TB_BOARD" ADD CONSTRAINT "PK_TB_BOARD" PRIMARY KEY (
	"B_NO"
);

ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"M_ID"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "PK_TB_COMMENT" PRIMARY KEY (
	"C_NO"
);

ALTER TABLE "TB_FILE" ADD CONSTRAINT "PK_TB_FILE" PRIMARY KEY (
	"F_NO"
);

ALTER TABLE "TB_BOARD_TYPE" ADD CONSTRAINT "PK_TB_BOARD_TYPE" PRIMARY KEY (
	"BT_NO"
);

